name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      REACT_APP_GOOGLE_CLIENT_ID: ${{ sercrets.REACT_APP_GOOGLE_CLIENT_ID }}
      REACT_APP_API_URL: ${{ sercrets.REACT_APP_API_URL }}
      REACT_APP_GOOGLE_MAP_API_KEY: ${{ sercrets.REACT_APP_GOOGLE_MAP_API_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: |
          npm ci
      - name: build application
        run: |
          npm run build
      - name: deploy hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project tm-evaluation-front
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
